import { Injectable, Logger, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Cron, CronExpression } from '@nestjs/schedule';
import { FlatPaymentPlan } from '../../payment-plans/entities/flat-payment-plan.entity';
import { FlatPaymentPlanService } from '../../payment-plans/services/flat-payment-plan.service';
import { DemandDraftTemplateService } from '../../payment-plans/services/demand-draft-template.service';
import { DemandDraft, DemandDraftStatus } from '../../demand-drafts/entities/demand-draft.entity';
import { PaymentSchedule, ScheduleStatus } from '../../payments/entities/payment-schedule.entity';
import { ConstructionFlatProgress } from '../entities/construction-flat-progress.entity';
import { ConstructionPhase } from '../entities/construction-tower-progress.entity';
import { MilestoneDetectionService, MilestoneMatch } from './milestone-detection.service';
import { Flat } from '../../flats/entities/flat.entity';
import { Customer } from '../../customers/entities/customer.entity';
import { Booking } from '../../bookings/entities/booking.entity';
import { Property } from '../../properties/entities/property.entity';
import { Tower } from '../../towers/entities/tower.entity';
import { buildDemandDraftHtml } from '../../../common/utils/demand-draft-html.builder';
import { SettingsService } from '../../settings/settings.service';
import { MailService } from '../../../common/mail/mail.service';

/**
 * Auto Demand Draft Generation Service
 * 
 * Automatically generates demand drafts when construction milestones are reached.
 * Uses templates to create HTML demand letters with all relevant details.
 */
@Injectable()
export class AutoDemandDraftService {
  private readonly logger = new Logger(AutoDemandDraftService.name);

  constructor(
    @InjectRepository(DemandDraft)
    private readonly demandDraftRepository: Repository<DemandDraft>,
    @InjectRepository(PaymentSchedule)
    private readonly paymentScheduleRepository: Repository<PaymentSchedule>,
    @InjectRepository(ConstructionFlatProgress)
    private readonly progressRepository: Repository<ConstructionFlatProgress>,
    @InjectRepository(Flat)
    private readonly flatRepository: Repository<Flat>,
    @InjectRepository(Customer)
    private readonly customerRepository: Repository<Customer>,
    @InjectRepository(Booking)
    private readonly bookingRepository: Repository<Booking>,
    @InjectRepository(Property)
    private readonly propertyRepository: Repository<Property>,
    @InjectRepository(Tower)
    private readonly towerRepository: Repository<Tower>,
    private readonly milestoneDetectionService: MilestoneDetectionService,
    private readonly flatPaymentPlanService: FlatPaymentPlanService,
    private readonly templateService: DemandDraftTemplateService,
    private readonly settingsService: SettingsService,
    private readonly mailService: MailService,
  ) {}

  /**
   * Scheduled job to auto-generate demand drafts
   * Runs every 2 hours
   * COMMENTED OUT FOR NOW - Enable when ready for automation
   */
  // @Cron(CronExpression.EVERY_2_HOURS)
  // async autoGenerateDemandDrafts(): Promise<void> {
  //   this.logger.log('Starting auto demand draft generation...');
  //   try {
  //     const matches = await this.milestoneDetectionService.detectMilestones();
  //     
  //     for (const match of matches) {
  //       try {
  //         await this.generateDemandDraft(match);
  //       } catch (error) {
  //         this.logger.error(`Failed to generate demand draft for flat ${match.flatPaymentPlan.flatId}:`, error);
  //       }
  //     }
  //
  //     this.logger.log(`Generated ${matches.length} demand draft(s)`);
  //   } catch (error) {
  //     this.logger.error('Error during auto demand draft generation:', error);
  //   }
  // }

  /**
   * Generate demand draft for a milestone match
   */
  async generateDemandDraft(match: MilestoneMatch, systemUserId?: string): Promise<DemandDraft> {
    const { flatPaymentPlan, milestoneSequence, constructionProgress, amount } = match;

    // Load all required data
    const flat = await this.flatRepository.findOne({
      where: { id: flatPaymentPlan.flatId },
      relations: ['property', 'tower'],
    });
    if (!flat) {
      throw new NotFoundException('Flat not found');
    }

    const customer = await this.customerRepository.findOne({
      where: { id: flatPaymentPlan.customerId },
    });
    if (!customer) {
      throw new NotFoundException('Customer not found');
    }

    const booking = await this.bookingRepository.findOne({
      where: { id: flatPaymentPlan.bookingId },
    });

    const milestone = flatPaymentPlan.milestones.find(m => m.sequence === milestoneSequence);
    if (!milestone) {
      throw new NotFoundException('Milestone not found');
    }

    // Calculate due date (default: 30 days from now)
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 30);

    const dueDateStr = dueDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
    const todayStr   = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
    const amountFmt  = Number(amount).toLocaleString('en-IN');
    const bookingRef = booking?.bookingNumber ?? flatPaymentPlan.bookingId.substring(0, 8).toUpperCase();
    const refNumber  = `DD-${bookingRef}-${String(milestoneSequence).padStart(2, '0')}`;

    // Store templateData for record keeping / template override
    const templateData: Record<string, any> = {
      customerName: customer.fullName,
      propertyName: flat.property?.name || 'N/A',
      towerName: flat.tower?.name || '',
      flatNumber: flat.flatNumber,
      milestoneName: milestone.name,
      milestoneDescription: milestone.description || '',
      milestoneSeq: milestoneSequence,
      amount: amountFmt,
      totalAmount: Number(flatPaymentPlan.totalAmount).toLocaleString('en-IN'),
      paidAmount: Number(flatPaymentPlan.paidAmount).toLocaleString('en-IN'),
      balanceAfterPayment: Number(Math.max(0, flatPaymentPlan.balanceAmount - amount)).toLocaleString('en-IN'),
      dueDate: dueDateStr,
      dateIssued: todayStr,
      refNumber,
      bookingNumber: booking?.bookingNumber || '',
      constructionPhase: milestone.constructionPhase || '',
      phasePercentage: milestone.phasePercentage,
      bankName: '[Bank Name — to be filled]',
      accountName: 'Eastern Estate',
      accountNumber: '[Account Number — to be filled]',
      ifscCode: '[IFSC Code — to be filled]',
      customerEmail: customer.email || '',
      customerPhone: customer.phoneNumber || '',
    };

    // Fetch company settings for bank details
    let companySettings: Awaited<ReturnType<SettingsService['get']>> | null = null;
    try {
      companySettings = await this.settingsService.get();
    } catch {
      this.logger.warn('Could not load company settings — bank details will show placeholder');
    }

    // Build canonical HTML using the shared builder (always used as primary)
    let htmlContent: string = buildDemandDraftHtml({
      refNumber,
      dateIssued: todayStr,
      customerName: customer.fullName,
      customerEmail: customer.email || undefined,
      customerPhone: customer.phoneNumber || undefined,
      propertyName: flat.property?.name || '',
      towerName: flat.tower?.name || undefined,
      flatNumber: flat.flatNumber,
      bookingNumber: booking?.bookingNumber || undefined,
      milestoneSeq: milestoneSequence,
      milestoneName: milestone.name,
      milestoneDescription: milestone.description || undefined,
      constructionPhase: milestone.constructionPhase || undefined,
      phasePercentage: milestone.phasePercentage ?? undefined,
      amount: amountFmt,
      dueDate: dueDateStr,
      totalAmount: String(flatPaymentPlan.totalAmount),
      paidAmount: String(flatPaymentPlan.paidAmount),
      balanceAfterPayment: String(Math.max(0, flatPaymentPlan.balanceAmount - amount)),
      // Property-level overrides → company settings fallback
      bankName: flat.property?.bankName || companySettings?.bankName || undefined,
      accountName: flat.property?.accountName || companySettings?.accountName || undefined,
      accountNumber: flat.property?.accountNumber || companySettings?.accountNumber || undefined,
      ifscCode: flat.property?.ifscCode || companySettings?.ifscCode || undefined,
      branch: flat.property?.branch || companySettings?.branch || undefined,
    });

    const subject = `Payment Demand – ${flat.flatNumber}${flat.tower?.name ? ` / ${flat.tower.name}` : ''} – ${milestone.name}`;
    let usedTemplateId: string | null = null;

    // If a DB template exists, use it instead (overrides canonical builder)
    try {
      const template = await this.templateService.findFirstActive();
      if (template) {
        const rendered = this.templateService.renderTemplate(template, templateData);
        htmlContent = rendered.htmlContent;
        usedTemplateId = template.id;
      }
    } catch {
      // Template table may not exist yet — canonical HTML already built above
    }

    // Try to create a payment schedule entry; skip silently if it fails
    let savedScheduleId: string | null = null;
    try {
      const paymentSchedule = this.paymentScheduleRepository.create({
        bookingId: flatPaymentPlan.bookingId,
        scheduleNumber: `${flatPaymentPlan.bookingId.substring(0, 8)}-${milestoneSequence}`,
        installmentNumber: milestoneSequence,
        totalInstallments: flatPaymentPlan.milestones.length,
        milestone: milestone.name,
        description: milestone.description,
        dueDate,
        amount,
        status: ScheduleStatus.PENDING,
        paidAmount: 0,
      });
      const savedSchedule = await this.paymentScheduleRepository.save(paymentSchedule);
      savedScheduleId = savedSchedule.id;
    } catch (err) {
      this.logger.warn('Could not create payment schedule entry (non-fatal):', err?.message);
    }

    // Build the draft title
    const towerLabel = flat.tower?.name ? `${flat.tower.name} / ` : '';
    const draftTitle = `${flat.flatNumber} / ${towerLabel}${milestone.name}`;

    // Create demand draft
    const demandDraft = this.demandDraftRepository.create({
      flatId: flatPaymentPlan.flatId,
      customerId: flatPaymentPlan.customerId,
      bookingId: flatPaymentPlan.bookingId,
      milestoneId: String(milestoneSequence),  // Use sequence number for consistent dedup with ConstructionWorkflowService
      title: draftTitle,
      amount,
      status: DemandDraftStatus.DRAFT,
      content: htmlContent,
      dueDate,
      metadata: {
        subject,
        templateData,
      },
      paymentScheduleId: savedScheduleId,
      flatPaymentPlanId: flatPaymentPlan.id,
      constructionCheckpointId: constructionProgress?.id ?? null,
      autoGenerated: true,
      requiresReview: true,
      templateId: usedTemplateId,
      templateData,
      generatedAt: new Date(),
      createdBy: systemUserId || null,
    });

    const savedDemandDraft = await this.demandDraftRepository.save(demandDraft);

    // Update flat payment plan milestone
    await this.flatPaymentPlanService.updateMilestone(
      flatPaymentPlan.id,
      milestoneSequence,
      {
        status: 'TRIGGERED',
        dueDate: dueDate.toISOString(),
        paymentScheduleId: savedScheduleId,
        demandDraftId: savedDemandDraft.id,
        constructionCheckpointId: constructionProgress?.id ?? null,
      },
      systemUserId || 'SYSTEM',
    );

    // Mark construction checkpoint as triggered (only if we have one)
    if (constructionProgress) {
      constructionProgress.isPaymentMilestone = true;
      constructionProgress.milestoneTriggered = true;
      constructionProgress.milestoneTriggeredAt = new Date();
      constructionProgress.demandDraftId = savedDemandDraft.id;
      if (savedScheduleId) {
        constructionProgress.paymentScheduleId = savedScheduleId;
      }
      await this.progressRepository.save(constructionProgress);
    }

    this.logger.log(
      `Generated demand draft ${savedDemandDraft.id} for flat ${flat.flatNumber}, milestone: ${milestone.name}`
    );

    return savedDemandDraft;
  }

  /**
   * Manually trigger demand draft generation for a specific milestone
   */
  async manualGenerateDemandDraft(
    flatPaymentPlanId: string,
    milestoneSequence: number,
    userId: string,
  ): Promise<DemandDraft> {
    const paymentPlan = await this.flatPaymentPlanService.findOne(flatPaymentPlanId);
    
    const milestone = paymentPlan.milestones.find(m => m.sequence === milestoneSequence);
    if (!milestone) {
      throw new NotFoundException('Milestone not found');
    }

    if (milestone.status !== 'PENDING') {
      throw new BadRequestException(
        `This milestone has already been ${milestone.status.toLowerCase()}. ` +
        `A demand draft may have already been generated for it. Check the Demand Drafts page.`
      );
    }

    // For construction-linked milestones, verify construction progress
    if (milestone.constructionPhase) {
      const canTrigger = await this.milestoneDetectionService.canTriggerMilestone(
        flatPaymentPlanId,
        milestoneSequence,
      );

      if (!canTrigger) {
        throw new BadRequestException(
          `Construction has not reached the required level for this milestone yet. ` +
          `Required: ${milestone.phasePercentage ?? 100}% of ${milestone.constructionPhase}. ` +
          `Please log the construction progress first and then generate the demand draft.`
        );
      }
    }

    // Get construction progress record (optional – token/down-payment milestones may not have one)
    let constructionProgress: ConstructionFlatProgress | null = null;

    if (milestone.constructionPhase) {
      constructionProgress = await this.progressRepository.findOne({
        where: {
          flatId: paymentPlan.flatId,
          phase: milestone.constructionPhase as ConstructionPhase,
        },
      });
      // Not fatal – draft can still be generated without the progress record link
      if (!constructionProgress) {
        this.logger.warn(
          `No construction progress record found for flat ${paymentPlan.flatId}, phase ${milestone.constructionPhase}. Draft will be created without checkpoint link.`
        );
      }
    }

    const match: MilestoneMatch = {
      flatPaymentPlan: paymentPlan,
      milestoneSequence,
      constructionProgress,
      milestoneName: milestone.name,
      amount: milestone.amount,
    };

    return await this.generateDemandDraft(match, userId);
  }

  /**
   * Approve and mark demand draft as ready to send
   */
  async approveDemandDraft(demandDraftId: string, userId: string): Promise<DemandDraft> {
    const demandDraft = await this.demandDraftRepository.findOne({
      where: { id: demandDraftId },
    });

    if (!demandDraft) {
      throw new NotFoundException('Demand draft not found');
    }

    demandDraft.status = DemandDraftStatus.READY;
    demandDraft.requiresReview = false;
    demandDraft.reviewedBy = userId;
    demandDraft.reviewedAt = new Date();
    demandDraft.updatedBy = userId;

    return await this.demandDraftRepository.save(demandDraft);
  }

  /**
   * Send demand draft to customer
   */
  async sendDemandDraft(demandDraftId: string, userId: string): Promise<DemandDraft> {
    const demandDraft = await this.demandDraftRepository.findOne({
      where: { id: demandDraftId },
    });

    if (!demandDraft) {
      throw new NotFoundException('Demand draft not found');
    }

    if (demandDraft.status !== DemandDraftStatus.READY) {
      throw new BadRequestException(
        `Demand draft is currently in "${demandDraft.status}" status. ` +
        `Please approve it first (set to READY) before sending.`
      );
    }

    // Fetch customer email
    let customerEmail: string | null = null;
    if (demandDraft.customerId) {
      const customer = await this.customerRepository.findOne({ where: { id: demandDraft.customerId } });
      customerEmail = customer?.email ?? null;
    }

    // Send email
    const emailSubject =
      (demandDraft.metadata as any)?.subject ||
      demandDraft.title ||
      `Payment Demand Notice — ₹${demandDraft.amount?.toLocaleString('en-IN')}`;

    if (customerEmail) {
      try {
        const result = await this.mailService.sendMail({
          to: customerEmail,
          subject: emailSubject,
          html: demandDraft.content || '<p>Please contact us for your payment demand details.</p>',
        });
        if (result.skipped) {
          this.logger.warn(`Email skipped (SMTP not configured) for draft ${demandDraftId}`);
        } else {
          this.logger.log(`Email sent to ${customerEmail} for draft ${demandDraftId}`);
        }
      } catch (mailErr: any) {
        // Don't block the status update if email fails — log and continue
        this.logger.error(`Email delivery failed for draft ${demandDraftId}: ${mailErr?.message}`);
      }
    } else {
      this.logger.warn(`Draft ${demandDraftId} has no customer email — skipping email send`);
    }

    demandDraft.status = DemandDraftStatus.SENT;
    demandDraft.sentAt = new Date();
    demandDraft.updatedBy = userId;

    this.logger.log(`Demand draft ${demandDraftId} marked as sent`);

    return await this.demandDraftRepository.save(demandDraft);
  }
}
