import { apiService } from './api';

export interface MilestoneMatch {
  flatPaymentPlan: any;
  milestoneSequence: number;
  constructionProgress: any;
  milestoneName: string;
  amount: number;
}

export interface ConstructionSummary {
  phases: Record<string, { progress: number; status: string }>;
  overallProgress: number;
}

export interface DemandDraft {
  id: string;
  flatId: string | null;
  customerId: string | null;
  bookingId: string | null;
  milestoneId: string | null;
  amount: number;
  status: 'DRAFT' | 'READY' | 'SENT' | 'FAILED';
  fileUrl: string | null;
  content: string | null;
  metadata: any;
  generatedAt: Date | null;
  sentAt: Date | null;
  autoGenerated: boolean;
  requiresReview: boolean;
  reviewedBy: string | null;
  reviewedAt: Date | null;
  reviewNotes: string | null;
  createdAt: string;
  updatedAt: string;
}

class ConstructionMilestonesService {
  /**
   * Get construction summary for a flat
   */
  async getConstructionSummary(flatId: string): Promise<ConstructionSummary> {
    // This would call a custom endpoint
    // For now, return empty data
    return {
      phases: {},
      overallProgress: 0,
    };
  }

  /**
   * Get detected milestones ready to trigger
   */
  async getDetectedMilestones(): Promise<MilestoneMatch[]> {
    return await apiService.get('/construction/milestones/detected');
  }

  /**
   * Get detected milestones for a specific flat
   */
  async getDetectedMilestonesForFlat(flatId: string): Promise<MilestoneMatch[]> {
    return await apiService.get(`/construction/milestones/flat/${flatId}`);
  }

  /**
   * Manually trigger demand draft generation
   */
  async triggerDemandDraft(flatPaymentPlanId: string, milestoneSequence: number): Promise<DemandDraft> {
    return await apiService.post('/construction/milestones/trigger-demand-draft', {
      flatPaymentPlanId,
      milestoneSequence,
    });
  }

  /**
   * Approve a demand draft
   */
  async approveDemandDraft(demandDraftId: string): Promise<DemandDraft> {
    return await apiService.put(`/demand-drafts/${demandDraftId}/approve`, {});
  }

  /**
   * Send a demand draft
   */
  async sendDemandDraft(demandDraftId: string): Promise<DemandDraft> {
    return await apiService.post(`/demand-drafts/${demandDraftId}/send`, {});
  }

  /**
   * Get demand draft preview
   */
  async getDemandDraftPreview(demandDraftId: string): Promise<{ html: string; metadata: any }> {
    return await apiService.get(`/demand-drafts/${demandDraftId}/preview`);
  }

  /**
   * Get payment summary for a flat
   */
  async getFlatPaymentSummary(flatId: string): Promise<{
    totalAmount: number;
    paidAmount: number;
    balanceAmount: number;
    completedMilestones: number;
    totalMilestones: number;
    nextMilestone: any;
  }> {
    return await apiService.get(`/construction/milestones/flat/${flatId}/summary`);
  }
}

export const constructionMilestonesService = new ConstructionMilestonesService();
