import { apiService } from './api';

export type DemandDraftStatus = 'DRAFT' | 'READY' | 'SENT' | 'PAID' | 'CANCELLED' | 'FAILED';

export interface DemandDraft {
  id: string;
  flatId?: string | null;
  customerId?: string | null;
  bookingId?: string | null;
  milestoneId?: string | null;
  amount: number;
  status: DemandDraftStatus;
  fileUrl?: string | null;
  content?: string | null;
  title?: string | null;
  dueDate?: string | null;
  autoGenerated?: boolean;
  requiresReview?: boolean;
  reviewedAt?: string | null;
  reviewedBy?: string | null;
  metadata?: any;
  generatedAt?: string | null;
  sentAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

class DemandDraftsService {
  async getDemandDrafts(): Promise<DemandDraft[]> {
    return await apiService.get<DemandDraft[]>('/demand-drafts');
  }

  async getDemandDraft(id: string): Promise<DemandDraft> {
    return await apiService.get<DemandDraft>(`/demand-drafts/${id}`);
  }

  async list(params: { flatId?: string; customerId?: string; bookingId?: string; milestoneId?: string }) {
    const query = new URLSearchParams();
    Object.entries(params || {}).forEach(([k, v]) => {
      if (v) query.append(k, v);
    });
    return await apiService.get<DemandDraft[]>(`/demand-drafts?${query.toString()}`);
  }

  async create(payload: Partial<DemandDraft>) {
    return await apiService.post<DemandDraft>('/demand-drafts', payload);
  }

  async update(id: string, payload: Partial<DemandDraft>) {
    return await apiService.patch<DemandDraft>(`/demand-drafts/${id}`, payload);
  }

  async updateDemandDraft(id: string, payload: Partial<DemandDraft>) {
    return await apiService.put<DemandDraft>(`/demand-drafts/${id}`, payload);
  }

  async approveDemandDraft(id: string): Promise<DemandDraft> {
    return await apiService.put<DemandDraft>(`/demand-drafts/${id}/approve`, {});
  }

  async sendDemandDraft(id: string, fileUrl?: string): Promise<DemandDraft> {
    return await apiService.post<DemandDraft>(`/demand-drafts/${id}/send`, { fileUrl });
  }

  async markSent(id: string, fileUrl?: string) {
    return await apiService.post<DemandDraft>(`/demand-drafts/${id}/send`, { fileUrl });
  }

  async getHtml(id: string): Promise<{ html: string }> {
    return await apiService.get<{ html: string }>(`/demand-drafts/${id}/html`);
  }

  async delete(id: string) {
    return await apiService.delete<void>(`/demand-drafts/${id}`);
  }
}

export const demandDraftsService = new DemandDraftsService();
export default demandDraftsService;
