'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import {
  ArrowLeft,
  FileText,
  Send,
  Download,
  Edit,
  Save,
  CheckCircle,
  Loader2,
  Eye,
  X,
} from 'lucide-react';
import { demandDraftsService } from '@/services/demand-drafts.service';
import { toast } from 'sonner';

interface DemandDraft {
  id: string;
  flatId: string;
  customerId: string;
  bookingId: string;
  milestoneId: string;
  amount: number;
  status: 'DRAFT' | 'READY' | 'SENT' | 'PAID' | 'CANCELLED';
  content: string;
  autoGenerated: boolean;
  requiresReview: boolean;
  generatedAt: string;
  reviewedAt?: string;
  reviewedBy?: string;
  sentAt?: string;
  fileUrl?: string;
  title?: string;
  dueDate?: string;
  metadata?: any;
  createdAt: string;
  updatedAt: string;
}

export default function DemandDraftDetailPage() {
  const router = useRouter();
  const params = useParams();
  const draftId = typeof params?.id === 'string' ? params.id : Array.isArray(params?.id) ? params.id[0] : '';

  const [draft, setDraft] = useState<DemandDraft | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState('');
  const [editedTitle, setEditedTitle] = useState('');
  const [editedAmount, setEditedAmount] = useState('');
  const [editedDueDate, setEditedDueDate] = useState('');
  const [previewMode, setPreviewMode] = useState(true);

  useEffect(() => {
    if (draftId) {
      loadDraft();
    }
  }, [draftId]);

  const loadDraft = async () => {
    try {
      setLoading(true);
      const data = await demandDraftsService.getDemandDraft(draftId);
      // Add default values for missing properties
      setDraft({
        ...data,
        autoGenerated: data.autoGenerated ?? false,
        requiresReview: data.requiresReview ?? false,
      });
      setEditedContent(data.content || '');
      setEditedTitle(data.title || '');
      setEditedAmount(data.amount?.toString() || '');
      setEditedDueDate(data.dueDate || '');
    } catch (error: any) {
      toast.error(error?.response?.data?.message || 'Failed to load demand draft');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!draft) return;

    try {
      setSaving(true);
      await demandDraftsService.updateDemandDraft(draft.id, {
        content: editedContent,
        title: editedTitle,
        amount: parseFloat(editedAmount),
        dueDate: editedDueDate,
      });
      toast.success('Demand draft updated successfully');
      setIsEditing(false);
      await loadDraft();
    } catch (error: any) {
      toast.error(error?.response?.data?.message || 'Failed to update demand draft');
      console.error(error);
    } finally {
      setSaving(false);
    }
  };

  const handleApprove = async () => {
    if (!draft) return;

    try {
      setSaving(true);
      await demandDraftsService.approveDemandDraft(draft.id);
      toast.success('Demand draft approved successfully');
      await loadDraft();
    } catch (error: any) {
      toast.error(error?.response?.data?.message || 'Failed to approve demand draft');
      console.error(error);
    } finally {
      setSaving(false);
    }
  };

  const handleSend = async () => {
    if (!draft) return;

    try {
      setSaving(true);
      await demandDraftsService.sendDemandDraft(draft.id);
      toast.success('Demand draft sent successfully');
      await loadDraft();
    } catch (error: any) {
      toast.error(error?.response?.data?.message || 'Failed to send demand draft');
      console.error(error);
    } finally {
      setSaving(false);
    }
  };

  const handleExport = () => {
    if (!draft || !draft.content) {
      toast.error('No content to export');
      return;
    }

    // Create a blob with HTML content
    const blob = new Blob([draft.content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `demand_draft_${draft.id}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Demand draft exported as HTML');
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'DRAFT':
        return 'bg-yellow-500';
      case 'READY':
        return 'bg-blue-500';
      case 'SENT':
        return 'bg-purple-500';
      case 'PAID':
        return 'bg-green-500';
      case 'CANCELLED':
        return 'bg-red-500';
      default:
        return 'bg-gray-500';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <div className="text-lg ml-2">Loading demand draft...</div>
      </div>
    );
  }

  if (!draft) {
    return (
      <div className="p-6 text-center text-red-500">
        <p>Demand draft not found.</p>
        <Button onClick={() => router.back()} className="mt-4">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="outline" onClick={() => router.back()}>
            <ArrowLeft className="mr-2 h-4 w-4" /> Back
          </Button>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">
              {draft.title || 'Demand Draft'}
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              Draft ID: <span className="font-mono">{draft.id}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Badge className={getStatusColor(draft.status)}>
            {draft.status}
          </Badge>
        </div>
      </div>

      {/* Actions Bar */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-wrap gap-3">
            {!isEditing && (
              <Button
                variant="outline"
                onClick={() => setIsEditing(true)}
                disabled={draft.status === 'SENT' || draft.status === 'PAID'}
              >
                <Edit className="mr-2 h-4 w-4" /> Edit Draft
              </Button>
            )}

            {isEditing && (
              <>
                <Button
                  onClick={handleSave}
                  disabled={saving}
                >
                  {saving ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Save className="mr-2 h-4 w-4" />
                  )}
                  Save Changes
                </Button>
                <Button
                  variant="outline"
                  onClick={() => {
                    setIsEditing(false);
                    setEditedContent(draft.content || '');
                    setEditedTitle(draft.title || '');
                    setEditedAmount(draft.amount?.toString() || '');
                  }}
                  disabled={saving}
                >
                  <X className="mr-2 h-4 w-4" /> Cancel
                </Button>
              </>
            )}

            {draft.status === 'DRAFT' && !isEditing && (
              <Button
                onClick={handleApprove}
                disabled={saving}
                className="bg-blue-600 hover:bg-blue-700"
              >
                {saving ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <CheckCircle className="mr-2 h-4 w-4" />
                )}
                Approve Draft
              </Button>
            )}

            {draft.status === 'READY' && !isEditing && (
              <Button
                onClick={handleSend}
                disabled={saving}
                className="bg-purple-600 hover:bg-purple-700"
              >
                {saving ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Send className="mr-2 h-4 w-4" />
                )}
                Send to Customer
              </Button>
            )}

            {!isEditing && (
              <>
                <Button
                  variant="outline"
                  onClick={() => setPreviewMode(!previewMode)}
                >
                  <Eye className="mr-2 h-4 w-4" />
                  {previewMode ? 'View HTML' : 'View Preview'}
                </Button>
                <Button
                  variant="outline"
                  onClick={handleExport}
                >
                  <Download className="mr-2 h-4 w-4" /> Export HTML
                </Button>
              </>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Main Content */}
        <div className="lg:col-span-2 space-y-6">
          {isEditing ? (
            <Card>
              <CardHeader>
                <CardTitle>Edit Demand Draft</CardTitle>
                <CardDescription>
                  Modify the content, title, amount, or due date
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="title">Title</Label>
                  <Input
                    id="title"
                    value={editedTitle}
                    onChange={(e) => setEditedTitle(e.target.value)}
                    placeholder="Payment Demand for Milestone"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="amount">Amount (₹)</Label>
                    <Input
                      id="amount"
                      type="number"
                      value={editedAmount}
                      onChange={(e) => setEditedAmount(e.target.value)}
                      placeholder="100000"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="dueDate">Due Date</Label>
                    <Input
                      id="dueDate"
                      type="date"
                      value={editedDueDate ? new Date(editedDueDate).toISOString().split('T')[0] : ''}
                      onChange={(e) => setEditedDueDate(e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="content">HTML Content</Label>
                  <Textarea
                    id="content"
                    value={editedContent}
                    onChange={(e) => setEditedContent(e.target.value)}
                    rows={20}
                    className="font-mono text-sm"
                    placeholder="<html>...</html>"
                  />
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardHeader>
                <CardTitle>Demand Draft Content</CardTitle>
                <CardDescription>
                  {previewMode ? 'Preview of the demand draft' : 'Raw HTML content'}
                </CardDescription>
              </CardHeader>
              <CardContent>
                {previewMode ? (
                  <div
                    className="border rounded-lg p-6 bg-white"
                    dangerouslySetInnerHTML={{ __html: draft.content || '<p>No content available</p>' }}
                  />
                ) : (
                  <pre className="text-xs bg-gray-50 p-4 rounded-lg overflow-x-auto border">
                    <code>{draft.content || 'No content available'}</code>
                  </pre>
                )}
              </CardContent>
            </Card>
          )}
        </div>

        {/* Details Sidebar */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Draft Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label className="text-xs text-muted-foreground">Milestone</Label>
                <div className="font-medium">{draft.milestoneId || 'N/A'}</div>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">Amount</Label>
                <div className="text-2xl font-bold">₹{draft.amount?.toLocaleString('en-IN')}</div>
              </div>

              {draft.dueDate && (
                <div>
                  <Label className="text-xs text-muted-foreground">Due Date</Label>
                  <div className="font-medium">
                    {new Date(draft.dueDate).toLocaleDateString('en-IN', {
                      day: '2-digit',
                      month: 'long',
                      year: 'numeric',
                    })}
                  </div>
                </div>
              )}

              <div>
                <Label className="text-xs text-muted-foreground">Flat ID</Label>
                <div className="font-mono text-sm">{draft.flatId}</div>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">Customer ID</Label>
                <div className="font-mono text-sm">{draft.customerId}</div>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">Auto-Generated</Label>
                <div>{draft.autoGenerated ? 'Yes' : 'No'}</div>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">Requires Review</Label>
                <div>{draft.requiresReview ? 'Yes' : 'No'}</div>
              </div>

              {draft.generatedAt && (
                <div>
                  <Label className="text-xs text-muted-foreground">Generated At</Label>
                  <div className="text-sm">
                    {new Date(draft.generatedAt).toLocaleString('en-IN')}
                  </div>
                </div>
              )}

              {draft.reviewedAt && (
                <div>
                  <Label className="text-xs text-muted-foreground">Reviewed At</Label>
                  <div className="text-sm">
                    {new Date(draft.reviewedAt).toLocaleString('en-IN')}
                  </div>
                </div>
              )}

              {draft.sentAt && (
                <div>
                  <Label className="text-xs text-muted-foreground">Sent At</Label>
                  <div className="text-sm">
                    {new Date(draft.sentAt).toLocaleString('en-IN')}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {draft.metadata && (
            <Card>
              <CardHeader>
                <CardTitle>Additional Info</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {draft.metadata.flatNumber && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Flat Number</Label>
                    <div className="font-medium">{draft.metadata.flatNumber}</div>
                  </div>
                )}
                {draft.metadata.propertyName && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Property</Label>
                    <div className="font-medium">{draft.metadata.propertyName}</div>
                  </div>
                )}
                {draft.metadata.towerName && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Tower</Label>
                    <div className="font-medium">{draft.metadata.towerName}</div>
                  </div>
                )}
                {draft.metadata.customerName && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Customer</Label>
                    <div className="font-medium">{draft.metadata.customerName}</div>
                  </div>
                )}
                {draft.metadata.constructionPhase && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Construction Phase</Label>
                    <div className="font-medium">{draft.metadata.constructionPhase}</div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
